### ISSUE TITLE
Simply Jetpacks seems to be incomplete. Check dependencies 

### ISSUE THREAD

**Issue by jurbania** [asphaltbuffet/societyrebirth#10]
1) Use JEI search simply jetpacks using @SimplyJetpacks
2) Observe several missing items

**Comment by jurbania** [comment]
Possibly check Thermal Expansion as dependency

**Comment by asphaltbuffet** [comment]
This pack is based on MC 1.10.2 and simply jetpacks 2 removed support for Thermal Expansion: 

> The new version of Simply Jetpacks does not support ThermalExpansion and Buildcraft anymore as they are not updated yet to 1.9.4 and beyond, but support for it will probably be added again as soon as these mods got updated. As a result of this change the only supported mod at the moment is EnderIO but there are more mods to be added to the list in the future.

Mekanism has it's own jetpack so we may just want to go with that instead.
