### ISSUE TITLE
Item Stacking Issue

### ISSUE THREAD

**Issue by slotharrow** [asphaltbuffet/societyrebirth#131]
**Describe the bug**
I've noticed Coal and Apple so far. Sometimes they don't stack. 

**To Reproduce**

**Expected behavior**
They should stack if they're the exact same item.

**Screenshots**
It would be two identical coal next to each other. 

**Environment (please complete the following information):**
 - Memory: [e.g. 16GB]
 - Server or Single Player? [y/n]
 - Link to crash log/logging:

**Additional context**

**Comment by asphaltbuffet** [comment]
Are they from same mod/core? Please get me some screenshots of this happening. Ideally with extra tooltips.

**Comment by asphaltbuffet** [comment]
Can't reproduce, closing until we see it again.
