### ISSUE TITLE
Enable Vanilla Tools

### ISSUE THREAD

**Issue by jurbania** [asphaltbuffet/societyrebirth#168]
Disabling vanilla tools breaks some recipes. This can cause issues with mods that use these items and JEI presenting these as "available".

Enable vanilla tools with a durability of "1". I understand this conflicts slightly with the opening tool set given to players to start out. This can be remedied by providing a chest at spawn with items of higher durability while crafted items will break quickly.

**Comment by asphaltbuffet** [comment]
can you give me an example? they are all supposed to be compatible

**Comment by asphaltbuffet** [comment]
was due to duplicate config files on server. no issue remains.
